add profile
airlab-unsri/website pull request #25
Opened 2020-01-27 04:34 UTC by AhmadAgus2010

2020-01-27 10:31 UTC, ariefrahmansyah requested changes
tolong tambahin foto ya

2020-02-06 03:43 UTC, ariefrahmansyah approved these changes

2020-02-06 03:49 UTC, imambungo approved these changes
lgtm :+1:

2020-02-06 05:22 UTC, ariefrahmansyah commented
kamu bisa langsung merge ya @imambungo

2020-02-06 05:42 UTC, merged