Add profil e : Inneke
airlab-unsri/website pull request #29
Opened 2020-01-28 00:32 UTC by kekek02

2020-01-28 01:58 UTC, ariefrahmansyah requested changes

2020-01-28 01:58 UTC, ariefrahmansyah commented on content/authors/kekek02/_index.md
> +- data processing
D dan P nya huruf gede ya

2020-01-28 01:58 UTC, ariefrahmansyah commented on content/authors/kekek02/_index.md
> +education
Ini kurang :

2020-01-28 02:00 UTC, ariefrahmansyah requested changes
Fotonya tolong dinamain avatar.jpg
Orientasinya juga tolong dibenerin ya

2020-01-28 09:21 UTC, kekek02 commented on content/authors/kekek02/_index.md
> +education
okee kak, maaf kak banyak yang diedit soalnya fotonya ga nemu yang pas

2020-01-28 09:49 UTC, ariefrahmansyah requested changes

2020-01-28 09:49 UTC, ariefrahmansyah commented on content/authors/kekek02/_index.md
> +  link:innekepuspitasari17@gmail.com
tolong kasih spasi ya habis `link:`

terus itu harusnya ditulis: `link: mailto:innekepuspitasari17@gmail.com`

2020-01-28 12:11 UTC, kekek02 commented on content/authors/kekek02/_index.md
> +  link:innekepuspitasari17@gmail.com
Okee kak

2020-01-28 12:54 UTC, ariefrahmansyah commented
Fotonya tolong dirotate dong. Btw, kamu bisa preview pr kamu di https://deploy-preview-29--airlab-unsri.netlify.com/

2020-02-06 04:07 UTC, imambungo approved these changes
lgtm :+1:

2020-02-06 05:23 UTC, ariefrahmansyah approved these changes

2020-02-06 05:44 UTC, merged